[package]
name = "evcxr_content"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
image = "0.24.8"
itertools = "0.12.0"
vorbis-encoder = "0.1.4"
